name: eram-chatbot
namespace: ${OKTETO_NAMESPACE}

build:
  rasa:
    context: .
    dockerfile: dockerfile

dev:
  rasa:
    image: ${OKTETO_BUILD_RASA_IMAGE}
    command: bash
    sync:
      - .:/app
    forward:
      - 5005:5005
      - 5055:5055
    volumes:
      - /app/models:/app/models

services:
  rasa:
    image: ${OKTETO_BUILD_RASA_IMAGE}
    ports:
      - 5005
      - 5055
    environment:
      - RASA_NLU_PERSISTENCE_DIR=/app/models