FROM rasa/rasa:3.6.20-spacy-en

WORKDIR /app
# Copy files
COPY . .

# Make all files writable
COPY models/20251209-223435-ivory-ayu.tar.gz /models/

# Expose Rasa port
EXPOSE 5005

# Default command
CMD ["rasa", "run", "--enable-api", "--cors", "*"]
