FROM rasa/rasa:3.6.20-spacy-en

WORKDIR /app
COPY . .

# Switch to root to allow training
USER root
RUN rasa train
# Switch back to default non-root user
USER 1001

EXPOSE 5005

CMD ["rasa", "run", "--enable-api", "--cors", "*", "--port", "5005"]
