# actions_server/Dockerfile
FROM rasa/rasa-sdk:latest

WORKDIR /app

COPY actions/ ./actions/

EXPOSE 5055

# Explicitly tell the container how to start
ENTRYPOINT ["rasa", "run", "actions", "--actions", "actions", "--port", "5055"]
